### ISSUE TITLE
Cannot read property due to assumed length

### ISSUE THREAD

**Issue by Glitch0011** [kopipejst/bar-graph#3]
Hi @kopipejst

On bar-graph.js#130 you've assumed the array `tCaption` has items because of an if-check a few lines above.

```
if (tCaption) {
    // fudge an ID for the fig caption
    var randID = makeid(5);

    figCaption = document.createElement('figcaption');
    figCaption.innerText = tCaption[0].innerText;
    figCaption.setAttribute('id', randID);
    holder.appendChild(figCaption);
    holder.setAttribute('role', 'image');
    holder.setAttribute('aria-labelledby', randID);
}
```
This is causing an error given the value is a valid array, but without any items in it, thus crashing on the `tCaption[0]` line.

This is probably because of a difference between how Chrome (my browser) and whatever browser you were using, responds to `tCaption = this.querySelectorAll('table caption');`, or perhaps that it's the only `querySelectorAll` that uses `this`.

I'm putting together a pull-request now to fix this with a simple length check.

**Comment by kopipejst** [comment]
thank you for the pull request. it's merged.
